global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Fawri Backend Metrics
  - job_name: 'fawri-backend'
    scheme: https
    static_configs:
      - targets: ['fawribackend-production.up.railway.app']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # - job_name: 'example_api'
  #   scheme: http
  #   static_configs:
  #     - targets: ['example_api:9091']